version: "3.8"

services:

  arsha:
    image: justadirck/angular-arsha:latest
    ports:
      - 81:80   

  iportfolio:
    image: justadirck/angular-iportfolio:latest
    ports:
      - 82:80      

  knight:
    image: justadirck/angular-knight:latest
    ports:
      - 83:80     

  niceadmin:
    image: justadirck/angular-niceadmin:latest
    ports:
      - 84:80         

  impact:
    image: justadirck/angular-impact:latest
    ports:
      - 85:80   

  gp:
    image: justadirck/angular-gp:latest
    ports:
      - 86:80        

  myresume:
    image: justadirck/angular-myresume:latest
    ports:
      - 87:80    

  herobiz:
    image: justadirck/angular-herobiz:latest
    ports:
      - 88:80  

  photofolio:
    image: justadirck/angular-photofolio:latest
    ports:
      - 89:80  

  upconstruction:
    image: justadirck/angular-upconstruction:latest
    ports:
      - 90:80  

  yummy:
    image: justadirck/angular-yummy:latest
    ports:
      - 91:80  

  zenblog:
    image: justadirck/angular-zenblog:latest
    ports:
      - 92:80                                                      

    
