version: "3.8"

services:

  angular:
    container_name: angular-zero
    image: justadirck/angular-zero:latest
    build:
      context: ..
      dockerfile: ./docker/dockerfile
    ports:
      - 80:80
      - 443:443
      - 4200:4200
