FROM node:lts-alpine as build

WORKDIR /app
COPY package.json ./
RUN npm install --force --verbose
COPY . .
RUN npm run build

FROM nginx:mainline-alpine as deploy

COPY --from=build /app/dist/* /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/nginx.conf
